name: R-CMD-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true  # Enables caching for faster builds
          extra-packages: |
            devtools
            covr
            testthat

      - name: Check package
        run: R CMD check .

      - name: Test coverage
        run: |
          Rscript -e "covr::codecov()"
